In [ ]:
'''from google.colab import drive
drive.mount('/content/drive')'''

"from google.colab import drive\ndrive.mount('/content/drive')"

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

import sklearn
from sklearn.preprocessing import OneHotEncoder

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_PV_INDIG.xlsx')
X = dataset.iloc[:, 0:].values

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
DF = pd.DataFrame(X)

In [ ]:
dataset

SpatialDimensionValueCode  TimeDim  NumericValue
0                         AFG   2010.0       63255.0
1                         AFG   2011.0       71968.0
2                         AFG   2012.0       53609.0
3                         AFG   2013.0       43369.0
4                         AFG   2014.0       58362.0
..                        ...      ...           ...
662                    GLOBAL   2016.0     2113043.0
663                    GLOBAL   2017.0     2203886.0
664                    GLOBAL   2018.0     1860705.0
665                    GLOBAL   2019.0     1981926.0
666                    GLOBAL   2020.0     1673062.0

[667 rows x 3 columns]

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria pv indig")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X[:, 2:] = sc.fit_transform(X[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,0] = le.fit_transform(X[:,0])
print(X)

In [ ]:
DF = pd.DataFrame(X)

In [ ]:
# DF.to_csv('/content/MALARIA_PV_INDIG (1).csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_PRES_CASES.xlsx' )
Y = dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria pres cases")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Y[:, 2:] = sc.fit_transform(Y[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y[:,0] = le.fit_transform(Y[:,0])
print(Y)

[[2 2010.0 0.03226858771334604]
 [2 2011.0 0.01726503208004978]
 [2 2012.0 -0.01995235916041206]
 ...
 [38 2018.0 4.235272150176265]
 [38 2019.0 1.3314266399992114]
 [38 2020.0 1.814117845634976]]


In [ ]:
DF = pd.DataFrame(Y)

In [ ]:
# DF.to_csv('/content/MALARIA_PRES_CASES - MALARIA_PRES_CASES.csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_PF_INDIG.xlsx')
Z = dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria pf indig")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Z[:, 2:] = sc.fit_transform(Z[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Z[:,0] = le.fit_transform(Z[:,0])
print(Z)

[[0 2010.0 -0.1988936057180585]
 [0 2011.0 -0.19895863188712526]
 [0 2012.0 -0.19946284549753607]
 ...
 [35 2018.0 6.169288940861964]
 [35 2019.0 12.535634990788342]
 [35 2020.0 10.1340808646768]]


In [ ]:
# DF = pd.DataFrame(Z)

In [ ]:
# DF.to_csv('/content/MALARIA_PF_INDIG.xlsx - MALARIA_PF_INDIG.csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_INDIG.xlsx')
W = dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria indig")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
W[:, 2:] = sc.fit_transform(W[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
W[:,0] = le.fit_transform(W[:,0])
print(W)

[[2 2010.0 -0.0731977238729506]
 [2 2011.0 -0.07657401758927562]
 [2 2012.0 -0.08561395257956561]
 ...
 [70 2018.0 8.640593954171855]
 [70 2019.0 10.89953934526379]
 [70 2020.0 10.496853716533877]]


In [ ]:
# DF = pd.DataFrame(W)

In [ ]:
# DF.to_csv('/content/MALARIA_INDIG - MALARIA_INDIG.csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_IMPORTED.xlsx')
V = dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria imported")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
V[:, 2:] = sc.fit_transform(V[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
V[:,0] = le.fit_transform(V[:,0])
print(V)

[[17 2010.0 -0.25149475578627684]
 [17 2011.0 -0.2733121559036098]
 [17 2012.0 -0.20639850291217232]
 ...
 [22 2018.0 7.596088360101869]
 [22 2019.0 7.474787791028469]
 [22 2020.0 5.435017464269205]]


In [ ]:
# DF = pd.DataFrame(V)

In [ ]:
# DF.to_csv('/content/MALARIA_IMPORTED - MALARIA_IMPORTED.csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_CONF_CASES.xlsx')
A = dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria conf cases")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
A[:, 2:] = sc.fit_transform(A[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
A[:,0] = le.fit_transform(A[:,0])
print(A)

[[1 2010.0 1.3259181911444657]
 [1 2011.0 1.468633188453847]
 [1 2012.0 2.530315444620176]
 ...
 [97 2018.0 -0.1869509508700365]
 [97 2019.0 -0.18695088455842077]
 [97 2020.0 -0.18695081824680504]]


In [ ]:
# DF = pd.DataFrame(A)

In [ ]:
# DF.to_csv('/content/MALARIA_CONF_CASES.csv - MALARIA_CONF_CASES.csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_TOTAL_CASES.xlsx')
H =  dataset.iloc[:, 0:].values

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria total cases")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
H[:, 2:] = sc.fit_transform(H[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
H[:,0] = le.fit_transform(H[:,0])
print(H)

[[2 2010.0 -0.03185577848149643]
 [2 2011.0 -0.03185577848149643]
 [2 2012.0 -0.03185577848149643]
 ...
 [38 2018.0 8.005603459278863]
 [38 2019.0 8.343598311593754]
 [38 2020.0 8.290699693733425]]


In [ ]:
# DF = pd.DataFrame(H)

In [ ]:
# DF.to_csv('/content/MALARIA_TOTAL_CASES - MALARIA_TOTAL_CASES (1).csv')

In [ ]:
dataset = pd.read_excel('/content/MALARIA_EST_INCIDENCE - MALARIA_EST_INCIDENCE (1).csv')
B = dataset.iloc[:, 0:].values

In [ ]:
dataset = dataset.dropna()

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria est incidence")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
DF = pd.DataFrame(B)
DF = DF.dropna()
DF.to_csv('/content/MALARIA_EST_INCIDENCE - MALARIA_EST_INCIDENCE (1).csv')

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
B[:, 2:] = sc.fit_transform(B[:, 2:])

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
B[:,0] = le.fit_transform(B[:,0])
print(B)

In [ ]:
print(B)

In [ ]:
DF = pd.DataFrame(B)

In [ ]:
DF.to_csv('/content/MALARIA_EST_INCIDENCE - MALARIA_EST_INCIDENCE (1).csv')

In [ ]:
dataset = pd.read_excel('/content/drive/MyDrive/malaria ka hackethon/malaria-cases/data/MALARIA_EST_MORTALITY.xlsx')

In [ ]:
dataset = dataset.dropna()

In [ ]:
figure = px.bar(dataset, x=dataset["SpatialDimensionValueCode"],
                y = dataset["NumericValue"],
                color = dataset["TimeDim"],
                title="Malaria est mortality")
figure.show()

In [ ]:
facing = dataset["TimeDim"].value_counts()
label = facing.index
counts = facing.values
color = ['gold', 'lightgreen']

fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.5)])
fig.update_layout(title_text='Yearwise')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=color, line=dict(color='black', width=3)))
fig.show()

In [ ]:
C = dataset.iloc[:, 0:].values
DF = pd.DataFrame(C)

In [ ]:
DF = DF.dropna()
DF.to_csv('/content/MALARIA_EST_MORTALITY - MALARIA_EST_MORTALITY (1).csv')
dataset = pd.read_csv('/content/MALARIA_EST_MORTALITY - MALARIA_EST_MORTALITY (1).csv')
C = dataset.iloc[:, 0:].values

In [ ]:
print(C)

[[0 'EUR' 2020.0 0.0]
 [1 'LSO' 2020.0 0.0]
 [2 'MUS' 2020.0 0.0]
 ...
 [2410 'ZWE' 2018.0 14.28382]
 [2411 'ZWE' 2019.0 17.3687]
 [2412 'ZWE' 2020.0 25.21474]]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()                                     
C[:, 3:] = sc.fit_transform(C[:, 3:])                ###error

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
C[:,2] = le.fit_transform(C[:,2])
print(C)

In [ ]:
 DF = pd.DataFrame(C)

In [ ]:
 DF.to_csv('/content/MALARIA_EST_MORTALITY - MALARIA_EST_MORTALITY (1).csv')